In [1]:
import numpy as np
print(np)

<module 'numpy' from 'c:\\python36\\lib\\site-packages\\numpy\\__init__.py'>


In [2]:
a2d = np.array(
    [
        [1,2,3,4], [6,7,8,9], [10,11,12,13]
    ]
)
a = a2d

In [6]:
##Sum
axis0Sum = np.sum(a, axis=0) # wil be [1+6+10, 2+7+11, 3+8+12, 4+9+13]
axis1Sum = np.sum(a, axis=1) #will be [1+2+3+4, 6+7+8+9, 10+11+12+13]
print ("Axis0shape=", axis0Sum.shape, "Axis0Sum=\n", axis0Sum)
print ("Axis1.shape=", axis1Sum.shape, "Axis1Sum=\n", axis1Sum)

Axis0shape= (4,) Axis0Sum=
 [17 20 23 26]
Axis1.shape= (3,) Axis1Sum=
 [10 30 46]


In [7]:
## mean
axis0Mean = np.mean(a, axis=0) #shape = (4,1) = [(1+6+10)/3, (2+7+11)/3,....(4+9+13)/3]
axis1Mean = np.mean(a, axis=1) #shape=(3,1) = [(1+2+3+4)/4, (6+7+8+9)/4, (10+11+12+13/4\
print ("Axis0Mean=\n", axis0Mean)
print ("axis1Mean=\n", axis1Mean)

Axis0Mean=
 [5.66666667 6.66666667 7.66666667 8.66666667]
axis1Mean=
 [ 2.5  7.5 11.5]


In [8]:
a3d =np.array(
    [
        [
            [1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]
        ],
        [
            [51,52, 53, 54, 55], [56, 57, 58, 59, 60], [61,62,63,64,65]
        ]

    ]
)
a = a3d

In [9]:
print (a.shape) #(2,3,5)
axis0Sum = np.sum(a, axis=0) # shape =(3,5) = [ [51+1, 52+2, 53+3, 54+4, 55+5], [56+6,...60+10], [61+11, ..65+15]]
axis1Sum = np.sum(a, axis=1) # shape = (2,5) = [[1+6+11, 2+7+12, 3+8+13,4+9+14, 5+10+15], [51+56+61 , 52+57+62, 53+58+63 ,54+59+64,  55+60+65] ]
axis2Sum = np.sum(a, axis=2) # shape(2,3) = [[1+2+3+4+5],[6+7+8+9+10],[11+12+13+14+15]], [51+52+53+..55],[56+57+..+60],[61+62+..65]]
print ("shape = ", axis0Sum.shape, "Axis0Sum=\n", axis0Sum)
print ("shape = ", axis1Sum.shape, "Axis1Sum=\n", axis1Sum)
print ("shape = ", axis2Sum.shape, "Axis2Sum=\n", axis2Sum)

(2, 3, 5)
shape =  (3, 5) Axis0Sum=
 [[52 54 56 58 60]
 [62 64 66 68 70]
 [72 74 76 78 80]]
shape =  (2, 5) Axis1Sum=
 [[ 18  21  24  27  30]
 [168 171 174 177 180]]
shape =  (2, 3) Axis2Sum=
 [[ 15  40  65]
 [265 290 315]]


In [10]:
axis0Mean = np.mean(a, axis=0) # shape =(3,5)
axis1Mean = np.mean(a, axis=1) # shape = (2,5)
axis2Mean = np.mean(a, axis=2) # shape(2,3)
print ("axis0Mean=\n", axis0Mean)
print ("axis1Mean=\n", axis1Mean)
print ("axis2Mean=\n", axis2Mean)

axis0Mean=
 [[26. 27. 28. 29. 30.]
 [31. 32. 33. 34. 35.]
 [36. 37. 38. 39. 40.]]
axis1Mean=
 [[ 6.  7.  8.  9. 10.]
 [56. 57. 58. 59. 60.]]
axis2Mean=
 [[ 3.  8. 13.]
 [53. 58. 63.]]
